-- V4.4 Growth Engine: analytics, trending and sponsor ads
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('pageview','view','like','share','video_play','ad_impression','ad_click')),
  content_type text check (content_type in ('article','video','site','ad')),
  content_id uuid,
  path text,
  referrer text,
  session_id text,
  created_at timestamptz not null default now()
);
create index if not exists analytics_events_created_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_content_idx on public.analytics_events(content_type, content_id, created_at desc);

create table if not exists public.trending_content (
  content_type text not null check (content_type in ('article','video')),
  content_id uuid not null,
  score numeric not null default 0,
  rank integer not null default 999,
  calculated_at timestamptz not null default now(),
  primary key(content_type, content_id)
);
create index if not exists trending_rank_idx on public.trending_content(rank, score desc);

create table if not exists public.ad_campaigns (
  id uuid primary key default gen_random_uuid(),
  advertiser_name text not null,
  title text not null,
  placement text not null check (placement in ('top','inline','sidebar','video')),
  image_url text,
  target_url text not null,
  alt_text text,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  active boolean not null default true,
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ad_campaigns_active_idx on public.ad_campaigns(active, placement, starts_at, ends_at);

alter table public.analytics_events enable row level security;
alter table public.trending_content enable row level security;
alter table public.ad_campaigns enable row level security;

-- No direct public inserts/reads are required; the server uses service-role for analytics.
drop policy if exists "public read trending" on public.trending_content;
create policy "public read trending" on public.trending_content for select using (true);
drop policy if exists "public read active ads" on public.ad_campaigns;
create policy "public read active ads" on public.ad_campaigns for select using (active = true and starts_at <= now() and (ends_at is null or ends_at >= now()));
drop policy if exists "editor manage ads" on public.ad_campaigns;
create policy "editor manage ads" on public.ad_campaigns for all using (public.is_editor()) with check (public.is_editor());

create or replace function public.rebuild_trending() returns void language plpgsql security definer set search_path=public as $$
begin
  truncate public.trending_content;
  insert into public.trending_content(content_type, content_id, score, rank)
  select content_type, content_id, score, row_number() over(order by score desc)::int
  from (
    select 'article'::text content_type, a.id content_id,
      (a.views * 1.0 + a.likes * 4.0 + a.shares * 7.0) /
      greatest(1, extract(epoch from (now() - coalesce(a.published_at,a.created_at)))/3600.0 + 2) as score
    from public.articles a where a.status='published'
    union all
    select 'video'::text, v.id,
      (v.views * 1.0 + v.likes * 4.0 + v.shares * 7.0) /
      greatest(1, extract(epoch from (now() - v.created_at))/3600.0 + 2) as score
    from public.videos v where v.status='published'
  ) ranked;
end;
$$;
revoke all on function public.rebuild_trending() from public;
grant execute on function public.rebuild_trending() to service_role;
create or replace function public.increment_ad_impressions(campaign_id uuid) returns void language sql security definer set search_path=public as $$ update public.ad_campaigns set impressions=impressions+1, updated_at=now() where id=campaign_id; $$;
create or replace function public.increment_ad_clicks(campaign_id uuid) returns void language sql security definer set search_path=public as $$ update public.ad_campaigns set clicks=clicks+1, updated_at=now() where id=campaign_id; $$;
revoke all on function public.increment_ad_impressions(uuid) from public;
revoke all on function public.increment_ad_clicks(uuid) from public;
grant execute on function public.increment_ad_impressions(uuid) to anon, authenticated;
grant execute on function public.increment_ad_clicks(uuid) to anon, authenticated;
